services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/docker/tools/dockge/data:/app/data
      - ${HOME}/docker/tools/dockge/stacks:${HOME}/docker/tools/dockge/stacks
      - ${HOME}/git:${HOME}/git:ro
    environment:
      - DOCKGE_STACKS_DIR=${HOME}/docker/tools/dockge/stacks
